export default {
    "two": "TWO",
    "title": 'Know Blockchain',
    "part": {
        "title_1": "2.1	 What Is Blockchain",
        "content_1": "Blockchain technology enables distributed public ledgers that hold immutable data in a secure and encrypted way and ensure that transactions can never be altered. While Bitcoin and other cryptocurrencies are the most popular examples of blockchain usage, this “distributed ledger technology” (DLT) is finding a broad range of uses. Data storage, financial transactions, real estate, asset management and many more uses are being explored.",
        "content_2": "A blockchain, originally block chain, is a growing list of records, called blocks, which are linked using cryptography. Each block contains a cryptographic hash of the previous block, a timestamp, and transaction data (generally represented as a Merkle tree).",
        "content_3": "By design, a blockchain is resistant to modification of the data. It is \"an open, distributed ledger that can record transactions between two parties efficiently and in a verifiable and permanent way\". For use as a distributed ledger, a blockchain is typically managed by a peer-to-peer network collectively adhering to a protocol for inter-node communication and validating new blocks. Once recorded, the data in any given block cannot be altered retroactively without alteration of all subsequent blocks, which requires consensus of the network majority. Although blockchain records are not unalterable, blockchains may be considered secure by design and exemplify a distributed computing system with high Byzantine fault tolerance. Decentralized consensus has therefore been claimed with a blockchain. ",
        "content_4": "Blockchain was invented by a person (or group of people) using the name Satoshi Nakamoto in 2008 to serve as the public transaction ledger of the cryptocurrency bitcoin. The identity of Satoshi Nakamoto is unknown. The invention of the blockchain for bitcoin made it the first digital currency to solve the double-spending problem without the need of a trusted authority or central server. The bitcoin design has inspired other applications, and blockchains that are readable by the public are widely used by cryptocurrencies. Blockchain is considered a type of payment rail. Private blockchain has been proposed for business use. ",
        "title_2": "2.2	 What is Hard Fork",
        "content_5": "A hard fork is a rule change such that the software validating according to the old rules will see the blocks produced according to the new rules as invalid. In case of a hard fork, all nodes meant to work in accordance with the new rules need to upgrade their software.",
        "content_6": "If one group of nodes continues to use the old software while the other nodes use the new software, a permanent split can occur. For example, Ethereum has hard-forked to \"make whole\" the investors in The DAO, which had been hacked by exploiting a vulnerability in its code. In this case, the fork resulted in a split creating Ethereum and Ethereum Classic chains. In 2014 the Nxt community was asked to consider a hard fork that would have led to a rollback of the blockchain records to mitigate the effects of a theft of 50 million NXT from a major cryptocurrency exchange. The hard fork proposal was rejected, and some of the funds were recovered after negotiations and ransom payment. Alternatively, to prevent a permanent split, a majority of nodes using the new software may return to the old rules, as was the case of bitcoin split on 12 March 2013.",
        "title_3": "2.3	 What is Smart Contract",
        "content_7": "Smart contracts were first proposed in the early 1990s by computer scientist, lawyer and cryptographer Nick Szabo, who coined the term. With the present implementations, based on blockchains, \"smart contract\" is mostly used more specifically in the sense of general purpose computation that takes place on a blockchain or distributed ledger. In this interpretation, used for example by the Ethereum Foundation or IBM, a smart contract is not necessarily related to the classical concept of a contract, but can be any kind of computer program.",
        "content_8": "A smart contract is a computer protocol intended to digitally facilitate, verify, or enforce the negotiation or performance of a contract. Smart contracts allow the performance of credible transactions without third parties. These transactions are trackable and irreversible. ",
        "content_9": "A smart contract also can be regarded as a secured stored procedure as its execution and codified effects like the transfer of some value between parties are strictly enforced and cannot be manipulated, after a transaction with specific contract details is stored into a blockchain or distributed ledger. That's because the actual execution of contracts is controlled and audited by the platform, not by any arbitrary server-side programs connecting to the platform.",
        "content_10": "Proponents of smart contracts claim that many kinds of contractual clauses may be made partially or fully self-executing, self-enforcing, or both. The aim of smart contracts is to provide security that is superior to traditional contract law and to reduce other transaction costs associated with contracting. Various cryptocurrencies have implemented types of smart contracts. ",
        "content_11": "In 2018, a US Senate report said: \"While smart contracts might sound new, the concept is rooted in basic contract law. Usually, the judicial system adjudicates contractual disputes and enforces terms, but it is also common to have another arbitration method, especially for international transactions. With smart contracts, a program enforces the contract built into the code.\"",
        "title_4": "2.4	 What is Airdrop",
        "content_12": "In the cryptocurrency and blockchain ecosystem, the term “Airdrop” refers to the distribution of digital assets to the public, either by virtue of holding a certain other token or simply by virtue of being an active wallet address on a particular blockchain.",
        "content_13": "Airdrops are often used as a marketing tool in order to raise awareness of the coin or token that is being distributed, as well as a method of diversifying the number of holders of that asset. ",
        "content_14": "Airdrop is a one-time distribution of coins to those members of the crypto community who perform specific actions or meet some criteria. For example, developers can send project coins to those who repost from their official pages on social networks or are the holder of a certain cryptocurrency. In exchange, those who want to receive free cryptocurrency become a means for instant distribution of information over the network.",
       
    }

}